server:
  error:
    include-messages: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/DriverTaxi
    username: postgres
    password: Vishnu@77
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
